name: swipe_tab_controller
description: "A flutter package that handles the swipe for the TabBarView, this moves to the other without too much delay"
version: 1.0.0
homepage: "https://github.com/SHAH-JI/swipe_tab_controller"

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

